// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://behjmwhafirdebfwwpez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlaGptd2hhZmlyZGViZnd3cGV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1NDUyODEsImV4cCI6MjA1MTEyMTI4MX0.6ksgslooF5_sq46SUbW0VcZ6VyJ5N4_vacahHvKIbz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);